
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Human_Resources
{

using System;
    
public partial class EmpleadosActivos
{

    public int Id { get; set; }

    public int Code { get; set; }

    public string Name { get; set; }

    public string Lastname { get; set; }

    public string Telephone { get; set; }

    public System.DateTime Admission { get; set; }

    public decimal Salary { get; set; }

    public string Status { get; set; }

    public int Departament { get; set; }

    public int Position { get; set; }

}

}
