
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Human_Resources
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Departure = new HashSet<Departure>();

        this.Holidays = new HashSet<Holidays>();

        this.License = new HashSet<License>();

        this.Permission = new HashSet<Permission>();

    }


    public int Id { get; set; }

    public int Code { get; set; }

    public string Name { get; set; }

    public string Lastname { get; set; }

    public string Telephone { get; set; }

    public System.DateTime Admission { get; set; }

    public decimal Salary { get; set; }

    public string Status { get; set; }

    public int Departament { get; set; }

    public int Position { get; set; }



    public virtual Departament Departament1 { get; set; }

    public virtual Position Position1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Departure> Departure { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Holidays> Holidays { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<License> License { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Permission> Permission { get; set; }

}

}
