

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Human_Resources
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class Human_ResourcesEntities2 : DbContext
{
    public Human_ResourcesEntities2()
        : base("name=Human_ResourcesEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Departament> Departament { get; set; }

    public virtual DbSet<Employee> Employee { get; set; }

    public virtual DbSet<Position> Position { get; set; }

    public virtual DbSet<Nomina> Nomina { get; set; }

    public virtual DbSet<Departure> Departure { get; set; }

    public virtual DbSet<Holidays> Holidays { get; set; }

    public virtual DbSet<License> License { get; set; }

    public virtual DbSet<Permission> Permission { get; set; }


    public virtual ObjectResult<Calculo> CalculoNomina()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Calculo>("CalculoNomina");
    }


    public virtual ObjectResult<EmpleadosActivos> EmpleadosActivos()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmpleadosActivos>("EmpleadosActivos");
    }


    public virtual ObjectResult<EmpleadosInactivos> EmpleadosInactivos()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmpleadosInactivos>("EmpleadosInactivos");
    }

}

}

