
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Human_Resources
{

using System;
    
public partial class DepartamentCreated
{

    public int Id { get; set; }

    public int Codigo { get; set; }

    public string Departamento { get; set; }

    public string Encargado { get; set; }

}

}
